[project]
name = "my-python-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Viktor Erlandsson", email = "72042504+trallan@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ruff>=0.16.10",
]

[project.scripts]
my-python-app = "my_python_app:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
